### ISSUE TITLE
double float 类型区别问题

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#100]
测试步骤：
double类型与float数据类型赋值超过38位
测试结果：
均返回：Error: decimal can only support precision up to 38; (state=,code=0)
建议：
两种类型取值范围可否进行区分

**Comment by hgs19921112** [comment]
quick start已经给出了注意点根据数据类型的不同添加后缀 double添加D 如2325.346346D float无需添加 float<decimal
