### ISSUE TITLE
primarykey 赋值为null成功

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#107]
测试步骤：
1.给一张random表插入一条数据，primarykey赋值为空
insert into all(name,primarykey) values ("a",'null');
2.select *from all;
测试结果：
success，查询显示primarykey为null
图片展示：
![image](https://user-images.githubusercontent.com/76684843/106850836-2f7f7b00-66f0-11eb-9b8c-81ee1e6c7fac.png)
![image](https://user-images.githubusercontent.com/76684843/106850858-38704c80-66f0-11eb-81e7-647223a59831.png)

**Comment by hgs19921112** [comment]
'null'是字符串 与null不等
