### ISSUE TITLE
distinct 去重操作多列情况下返回结果为json，而非列表形式

### ISSUE THREAD

**Issue by zhou-anxing** [lucene-cn/lxdb#112]
问题描述：distinct查询操作，多列去重时现实json键值对格式数据，格式不匹配
期望结果：distinct 去重操作结果显示为列表格式
问题截图：
![image](https://user-images.githubusercontent.com/76685477/106870374-010f9900-670c-11eb-8fde-93a02bfd057d.png)

**Comment by hgs19921112** [comment]
查询时请用distinct id,name 不要添加括号
