### ISSUE TITLE
data、string、text、textik、time类型赋值boolean类型值成功

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#113]
测试步骤：如标题几个类型赋值boolean类型值true、false
数据表类型，random默认主键表
展示列所对应的数据类型如下：
fenci  text_i
fneci8 textik
name string
time data
测试sql：
insert into all(fenci) values (true);
insert into all(fenci8) values (true);
insert into all(name) values (true);
insert into all(time) values (false);
测试结果：
success，插入成功
![image](https://user-images.githubusercontent.com/76684843/106874657-cc521080-6710-11eb-9cb8-9e031acc5046.png)

**Comment by gleonSun** [comment]
BUG 描述不够清晰，需要加上表结构，例如主键类型等信息附上

**Comment by hgs19921112** [comment]
text_i，textik是通过获取字符串来完成索引数据的 ,而当输入为boolean类型时，可以讲true/false转换为string所以可以插入成功，不是bug。
