### ISSUE TITLE
模糊查询,匹配任意一个字符语法 (_ ?)

### ISSUE THREAD

**Issue by zhou-anxing** [lucene-cn/lxdb#114]
问题描述：模糊匹配时,匹配任意字符的符号 问号？ 是否可用,目前?不可用，_符号可用(此方面文档未明确)
问题截图：
![image](https://user-images.githubusercontent.com/76685477/106874551-a6c50700-6710-11eb-96b5-b1c7d521cf5d.png)

**Comment by hgs19921112** [comment]
like只支持'_'和‘%’吧？
