### ISSUE TITLE
Error: DataType y_float_is is not supported.; line 5 pos 9 (state=,code=0)

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#119]
0: jdbc:hive2://localhost:10000/default> CREATE TABLE IF NOT EXISTS stu(
0: jdbc:hive2://localhost:10000/default> id int_is
0: jdbc:hive2://localhost:10000/default> ,name string_is
0: jdbc:hive2://localhost:10000/default> ,score double_is
0: jdbc:hive2://localhost:10000/default> ,consume y_float_is
0: jdbc:hive2://localhost:10000/default> , weight y_long_is)TBLPROPERTIES(
0: jdbc:hive2://localhost:10000/default> "regionSplitter"="custom",
0: jdbc:hive2://localhost:10000/default> "splits"="1,2,3,4,5,6,7,8,9,a,b,c,d,e,f"
0: jdbc:hive2://localhost:10000/default> );
Error: DataType y_float_is is not supported.; line 5 pos 9 (state=,code=0)
0: jdbc:hive2://localhost:10000/default> CREATE TABLE IF NOT EXISTS stu(
0: jdbc:hive2://localhost:10000/default> id int_is
0: jdbc:hive2://localhost:10000/default> ,name string_is
0: jdbc:hive2://localhost:10000/default> ,score double_is
0: jdbc:hive2://localhost:10000/default> ,consume y_float_is
0: jdbc:hive2://localhost:10000/default> , weight y_long_is)TBLPROPERTIES(
0: jdbc:hive2://localhost:10000/default> "regionSplitter"="custom",
0: jdbc:hive2://localhost:10000/default> "splits"="1,2,3,4,5,6,7,8,9,a,b,c,d,e,f"
0: jdbc:hive2://localhost:10000/default> );
Error: DataType y_float_is is not supported.; line 5 pos 9 (state=,code=0)
0: jdbc:hive2://localhost:10000/default> 
0: jdbc:hive2://localhost:10000/default> 
0: jdbc:hive2://localhost:10000/default>

**Comment by hgs19921112** [comment]
已修改
