### ISSUE TITLE
文档补充：Decimal，Double类型转换条件

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#122]
表字段类型为double ，在spark中13242.353为Decimal，13242.353D为Double，如果数字不加D会导致数据类型转换失败。
例如：insert into all(scort9) values (array(233333333333333.33333333333333333333333D,2.3333333333333333333333333D));则完全没有问题，所以需要根据数据类型的不同添加后缀来防止类型转换错误。
目前测试情况：
1.double类型数据插入值 总长度最高为38位，小数点前至多13位，小数点之后之多25位（不包含符号位），此范围内不需要再数字末尾加D
2.超过上述限制需在数字末尾加上D来进行转换，需标明加入D后的长度限制

**Comment by hgs19921112** [comment]
DML章节添加了在insert时需要注意的点。
