### ISSUE TITLE
使用if not exists创建一张已存在的数据表，增加结果反馈提示

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#124]
测试步骤：
1.create table all1(name string);
2.create table if not exists all1(id int);
测试结果：
反馈结果均为success
解析：if not exists的意思是在表存在的时候避免抛出错误，所以if not exists的时候语句执行成功，但是表结构没有改变是正常的。
建议：
上述解释表明，if not exists只有判断数据表是否存在的功能，建议使用if not exists创建表时，若数据表已存在追加反馈提示数据表已存在，类似：0 rows affected, 1 warning此种反馈形式
![image](https://user-images.githubusercontent.com/76684843/108822989-cd34de80-75fa-11eb-913d-632ba185fb6c.png)

**Comment by hgs19921112** [comment]
if not exists 的本意是忽略错误，所以无需修改
