### ISSUE TITLE
文档修改

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#125]
原文档内容：
double添加‘D’后缀，如:388.7D、388D
smallint添加‘S’后缀，如:28S
tinyint添加‘Y’后缀，如:8Y
bigint添加‘L’后缀，如:9875337333L
integer无需添加后缀
bigdecimal添加‘BD’后缀，如:769347503BD
建议：
将文档中所提到的hive数据类型，转换为lxdb的数据类型，方便读者直接查看
![image](https://user-images.githubusercontent.com/76684843/108938919-dc17a180-768b-11eb-9950-4cc2dd739a80.png)

**Comment by hgs19921112** [comment]
已修改
