### ISSUE TITLE
分词text_ik 类型 查询单个字符串失败

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#132]
测试步骤：
数据表为random，fenci3字段类型 text_ik
insert into all(fenci3) values ("transwarp Inceptor可提供完整的SQL支持，支持主流的SQL模块化扩展，兼容通用开发框架和工具，支持事务特性保证数据的准确性");
select * from all where fenci3 = '支确';
结果：
查询失败

![image](https://user-images.githubusercontent.com/76684843/109100800-8a8d1680-7760-11eb-9ad4-7df7728ba74c.png)

**Comment by sun897827804** [comment]
ik分词器切分的时候并不是随意将某几个汉字组合在一起，不能确保一句话中随意2个汉字都能被切出来，默认使用ik中分词的岐义消除算法：
规则1：比较有效文本长度
规则2: 比较词元个数，越少越好
规则3: 路径跨度越大越好
规则4: 根据统计学结论，逆向切分概率高于正向切分
规则5: 词长越平均越好(词元长度相乘)
规则6: 词元位置权重比较(词元长度积),含义是选取长的词元位置在后的集合

例如：取“张三说的确实在理”一句话中LexemePath不交叉词元，组成新的LexemePath：
L1对应的词元链如下:
L11:{张三}
L12:{张}
L13:{三}

L2对应词元链：
L2:{说}

L3对应的词元链如下
L31:{的,确实,在理}
L32:{的确,实,在理}
L33:{的确,实在,理}
L34:{的确,实在}
L35:{确实,在理}
L36:{确实}

L3词元链歧义消除示例：
按规则1比较L3有效的文本长度：
L31:{的,确实,在理}
L32:{的确,实,在理}
L33:{的确,实在,理}

按规则5，6权重比较
L31:{的,确实,在理}1*1+2*2+3*2=11
L32:{的确,实,在理} 1*2+2*1+3*2=10
L33:{的确,实在,理} 1*2+2*2+3*1=9

最后的分词结果:张三,说,的,确实,在理
