### ISSUE TITLE
geopoint_ism数据类型赋值问题

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#136]
测试步骤：
1.创建一张默认主键表 create table all2(geo geopoint_ism);
2.按正确赋值格式赋值 insert into table all2(geo) values (array('2.33,3.44'));
3.查询数据表select * from all2;
3.赋值double类型，并在数字后加入字符D insert into table all2(geo) values (array('2.33,3.44D'));
4.查询数据表select * from all2;
测试结果：
第四步赋值成功，插入成功后，查询该表，报异常

![image](https://user-images.githubusercontent.com/76684843/109130475-bd4d0400-778c-11eb-8037-76e766853b0b.png)
![image](https://user-images.githubusercontent.com/76684843/109131404-becafc00-778d-11eb-820e-c068ab66ce3d.png)

**Comment by sun897827804** [comment]
已修复
