### ISSUE TITLE
update更新使用不存在的primarykey，成功

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#139]
操作前提：
random数据表
操作步骤：
update table all set age6 = 1000 where primarykey ="sdsdf";使用不存在的primarykey
结果：
success
![image](https://user-images.githubusercontent.com/76684843/109764297-57e69080-7c2e-11eb-9a6f-dda14230349e.png)

**Comment by hgs19921112** [comment]
主键不存在 不影响更新语句的执行 ，这个没有问题。
