### ISSUE TITLE
text类型 能否切分英文单词

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#143]
测试前提：
数据表random数据表 habby2数据类型为text_is
测试步骤：
select * from random_ciku where habby2 ='H';
测试结果：
查询不出结果
测试疑问：
text类型是否支持英文单词的切分

**Comment by sun897827804** [comment]
不支持将单词切分成一个个字母，只能切语句。例如：“It is a nice day today”，切分效果：“it”、“is”、“a”、“nice”、“day”、“today”，详细已沟通。
