### ISSUE TITLE
textik 类型查询条件为一个字也可以识别

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#145]
测试前提：
数据表为random数据表
habby7数据类型为 textik
词库未包含 ‘的’
测试步骤：
select * from random_ciku where habby7 like '的';
测试结果：
查询出所有habby7列包含d的数据，   textik类型应该是按词来切分，改sql查询条件为单个汉字，为何能查询出结果，测试了几个其他无法组成词语的单个字也可以成功比如  ‘一’  ‘很’

![image](https://user-images.githubusercontent.com/76684843/110900074-26ac4580-833d-11eb-9f28-b341c35d52dd.png)

**Comment by sun897827804** [comment]
目前采用最小粒度切分算法，如果想提升切分的准确性及常用语气词助词等之类的过滤，需要扩展词库，详细已线下沟通
