### ISSUE TITLE
wiki补充敏感词设定限制

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#146]
测试前提：
设置敏感词‘德邦’
测试步骤：
select * from random_ciku where habby6 ='德邦';
测试结果：
查询出包含德邦的数据
textik类型 未被切分出来的词，就算设定了敏感词，也可以查询到
避免方法：
设置的敏感词需先被切分出来，最好的办法就是添加的敏感词也添加至词库内

![image](https://user-images.githubusercontent.com/76684843/110924171-b1506d00-835c-11eb-9408-7c57da76709c.png)

**Comment by sun897827804** [comment]
分词文档补充，如有遗漏，请提issues。https://github.com/lucene-cn/lxdb/wiki/participles
