### ISSUE TITLE
kafka导入数据失败

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#39]
无任何反应

**Comment by muyannian** [comment]
private def ignoreNonSparkProperties(): Unit = {
    sparkProperties.keys.foreach { k =>
      if (!k.startsWith("spark.")) {
        sparkProperties -= k
        logWarning(s"Ignoring non-Spark config property: $k")
      }
    }
  }

**Comment by muyannian** [comment]
修改为 如下 
   */
  private def ignoreNonSparkProperties(): Unit = {
    sparkProperties.keys.foreach { k =>
      if (!k.startsWith("spark.") && !k.startsWith("hydrogen.") && !k.startsWith("lxdb.")) {
        sparkProperties -= k
        logWarning(s"Ignoring non-Spark config property: $k")
      }
    }
  }

**Comment by muyannian** [comment]
spark.hydrogen.schedule.refresh.scheduleDelay 5
spark.hydrogen.kafka.bootstrap.servers test1:9092
spark.hydrogen.kafka.bufferThreshold 500
spark.hydrogen.kafka.topics hydrogen
spark.hydrogen.kafka.scheduleDelay 30000

**Comment by hgs19921112** [comment]
由于配置非spark.开头，被过滤，无法加载kafka配置。母延年已修改
