### ISSUE TITLE
kafka导入的这里判断有问题operation 的取值有问题

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#43]
kafka导入的这里判断有问题operation 的取值有问题
operation 的取值有问题  跟put不是同一个值 

   if (puts.size() >= bufferThreshold) {
                                    try (Table table = getConnection().getTable(TableName.valueOf(tableName))) {
   if (operation == null || operation.equals("") || operation.equals("insert")) {
                                            for (Object ob : puts) {
                                                table.put((Put) ob);
                                            }

**Comment by chenyu-hash** [comment]
bug已经解决
