### ISSUE TITLE
研究updateIndex

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#46]
目前lucene支持updateDocuments,可以给一批rowkey ,一次性更新一批document
但目前还不支持updateIndexs,给一个索引,按照索引中的rowkey一次性更新

这个需要封装成原子性,目前优先级低,先实现按照索引delete的query

**Comment by muyannian** [comment]
如若耗时很久,或者代码改动量很大,  改为与updateDocument加读锁,    delete(queue)+addIndex加写锁的方式来实现

**Comment by hgs19921112** [comment]
sun wei 已完成
