### ISSUE TITLE
按照组键更新,数据没有排除掉

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#52]
1 row selected (0.365 seconds)
0: jdbc:hive2://localhost:10000/default> select * from  hydrogen_primary where name='zhangsan1' ;
+-----------+------------+--------+--+
|    id     |    name    | score  |
+-----------+------------+--------+--+
| 1         | zhangsan1  | 1.0    |
| 1         | zhangsan1  | 1.0    |
| 20000001  | zhangsan1  | 1.0    |
| 20000001  | zhangsan1  | 1.0    |
+-----------+------------+--------+--+
4 rows selected (1.419 seconds)
0: jdbc:hive2://localhost:10000/default> select * from  hydrogen_primary where name='zhangsan1' ;
+-----------+------------+--------+--+
|    id     |    name    | score  |
+-----------+------------+--------+--+
| 1         | zhangsan1  | 1.0    |
| 1         | zhangsan1  | 1.0    |
| 20000001  | zhangsan1  | 1.0    |
| 20000001  | zhangsan1  | 1.0    |
+-----------+------------+--------+--+
4 rows selected (0.269 seconds)
0: jdbc:hive2://localhost:10000/default> select * from  hydrogen_primary where name='zhangsan2' ;
+-----------+------------+--------+--+
|    id     |    name    | score  |
+-----------+------------+--------+--+
| 2         | zhangsan2  | 2.0    |
| 2         | zhangsan2  | 2.0    |
| 20000002  | zhangsan2  | 2.0    |
| 20000002  | zhangsan2  | 2.0    |
+-----------+------------+--------+--+
4 rows selected (0.321 seconds)
0: jdbc:hive2://localhost:10000/default> show create table  hydrogen_primary ;
+----------------------------------------------------------------------------------------------+--+
|                                          create_tb                                           |
+----------------------------------------------------------------------------------------------+--+
| CREATE TABLE `hydrogen_primary` (
  `id` int_is,
  `name` string_is,
  `score` double_is
)
  |
+----------------------------------------------------------------------------------------------+--+
1 row selected (0.062 seconds)
0: jdbc:hive2://localhost:10000/default> select id,primaryKey  from  hydrogen_primary where name='zhangsan2' ;
Error: cannot resolve '`primaryKey`' given input columns: [default.hydrogen_primary.id, default.hydrogen_primary.name, default.hydrogen_primary.score]; line 1 pos 10 (state=,code=0)
0: jdbc:hive2://localhost:10000/default> select id  from  hydrogen_primary where name='zhangsan2' ;
+-----------+--+
|    id     |
+-----------+--+
| 2         |
| 2         |
| 20000002  |
| 20000002  |
| 30000002  |
+-----------+--+

**Comment by muyannian** [comment]
TermEnumerationNode 中的循环写错了 正确的应该是while 而不是true    

private static final class TermEnumerationNode extends Node<Enumeration<Term>> {

        TermEnumerationNode(Enumeration<Term> item) {
            super(item);
        }

        @Override
        void apply(BufferedUpdates bufferedDeletes, int docIDUpto) {
            while (item.hasMoreElements()) {
                bufferedDeletes.addTerm(item.nextElement(), docIDUpto);
            }
        }

    }

**Comment by chenyu-hash** [comment]
bug已经解决
