### ISSUE TITLE
nrt索引存在问题

### ISSUE THREAD

**Issue by muyannian** [lucene-cn/lxdb#53]
double nrtCacheMaxMergeSizeMB = configuration.getInt(NRTCACHINGDIRECTORY_MAXMERGESIZEMB, 16);
            double nrtCacheMaxCacheMB = configuration.getInt(NRTCACHINGDIRECTORY_MAXCACHEMB, 32);

依然存在内存占满的情况 

num     #instances         #bytes  class name
----------------------------------------------
   1:      27233575     2218018776  [C
   2:      26958053     1078322120  org.apache.lucene.store.RAMFile
   3:      26012246      832391872  java.util.HashMap$Node
   4:      25929120      829731840  java.util.concurrent.ConcurrentHashMap$Node
   5:      27232440      653578560  java.lang.String
   6:      27135401      651249624  java.util.ArrayList
   7:         15302      420839416  [Ljava.util.HashMap$Node;
   8:          2773      270800816  [Ljava.util.concurrent.ConcurrentHashMap$Node;
   9:        542216      145550480  [B
  10:       1360448       76185088  java.util.HashMap$TreeNode
  11:       1249964       59998272  java.util.concurrent.ConcurrentHashMap$TreeNode
  12:        686731       16481544  org.apache.lucene.util.BytesRef
  13:        199409       15408336  [Ljava.lang.Object;
  14:        422091       13506912  org.wltea.analyzer.dic.DictSegment
  15:          6903       12334616  [I
  16:        343028       10976896  org.apache.hadoop.hbase.regionserver.NoTagByteBufferChunkKeyValue
  17:        343107        8234568  java.util.concurrent.ConcurrentSkipListMap$Node
  18:        171504        8232192  org.apache.lucene.document.FieldType
  19:        133566        6411168  java.util.concurrent.ConcurrentHashMap$TreeBin
  20:           900        6348456  [J
  21:        177553        5681696  [Lorg.wltea.analyzer.dic.DictSegment;
  22:        171500        5488000  org.apache.lucene.document.BinaryDocValuesField
  23:        171500        5488000  org.apache.lucene.document.DoublePoint
  24:        171500        5488000  org.apache.lucene.document.Field
  25:        171500        5488000  org.apache.lucene.document.StringField
  26:        171500        4116000  org.apache.lucene.index.Term
  27:        171372        4112928  java.util.concurrent.ConcurrentSkipListMap$Index
  28:        167880        4029120  org.apache.lucene.search.BooleanClause
  29:        167880        4029120  org.apache.lucene.search.TermQuery
  30:        171500        2744000  org.apache.lucene.document.Document
  31:         16596        1839232  java.lang.Class
  32:         20326        1463472  java.lang.reflect.Field
  33:         39009        1248288  java.util.concurrent.atomic.LongAdder
  34:         25688        1233024  java.util.HashMap
  35:         35720        1143040  com.esotericsoftware.kryo.Registration
  36:         11527        1014376  java.lang.reflect.Method
  37:          1248         818688  org.apache.hbase.thirdparty.io.netty.util.internal.shaded.org.jctools.queues.MpscArrayQueue
  38:         32768         786432  org.apache.hadoop.hbase.regionserver.wal.RingBufferTruck
  39:           550         681424  [Lorg.apache.lucene.search.BooleanClause;
  40:         17992         575744  java.util.Hashtable$Entry
  41:          8360         535040  com.esotericsoftware.kryo.serializers.UnsafeCacheFields$UnsafeObjectField
  42:         16489         527648  java.lang.invoke.LambdaForm$Name
  43:         18998         507968  [Ljava.lang.String;
  44:         26337         421392  java.lang.Object
  45:         14722         407048  [Ljava.lang.Class;
  46:          9276         371040  org.apache.hadoop.hbase.KeyValue$KeyOnlyKeyValue
  47:           867         368568  [Ljava.lang.invoke.LambdaForm$Name;
  48:         13490         323760  com.esotericsoftware.kryo.Kryo$DefaultSerializerEntry
  49:          4001         320080  org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$MutationProto
  50:          1990         318400  org.apache.hadoop.hdfs.protocol.DatanodeInfoWithStorage
  51:          3800         304000  com.esotericsoftware.kryo.serializers.FieldSerializer
  52:          3546         226944  io.netty.buffer.PoolSubpage
  53:          3426         219264  java.util.concurrent.ConcurrentHashMap
  54:          4560         218880  com.esotericsoftware.kryo.serializers.UnsafeCacheFields$UnsafeIntField
  55:          2688         215176  [Lscala.collection.mutable.HashEntry;
  56:            63         206016  [Ljava.nio.channels.SelectionKey;

**Comment by muyannian** [comment]
我猜测问题的原因在于lucene的RAMDirectory如下方法统计的不准确导致


@Override
  public final long ramBytesUsed() {
    ensureOpen();
    return sizeInBytes.get();
  }

**Comment by muyannian** [comment]
这个类实现的确实有问题,考虑lsql的做法,精确计算,当outputstream写入超过多少以后,强制刷盘

**Comment by chenyu-hash** [comment]
bug已经解决
