### ISSUE TITLE
重复创建同名数据表，新增数据表字段，表字段未更新

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#68]
测试步骤：
1.创建名为dan的数据表，表字段为 （name string_is,id int）
2.使用if not exists创建相同的数据表dan，新增表字段year int
3.查询表，select 8 from dan;
结果：
步骤1、2数据表创建成功success，步骤三，查询表，结果表字段并未更新，仍为步骤一创建的表字段，步骤二新增的表字段未展示出
期待：
使用if not exists创建相同的数据表dan，新增表字段year int，查询结果应替换原表，表字段类型应与新创建的覆盖表一致
详细步骤展示：

![1611546488(1)](https://user-images.githubusercontent.com/76684843/105661925-8ffd0400-5f09-11eb-8bfc-7643173a8c23.jpg)

**Comment by hgs19921112** [comment]
if not exists的意思是在表存在的时候避免抛出错误，所以if not exists的时候语句执行成功，但是表结构没有改变是正常的。
