### ISSUE TITLE
创建一个只包含主键字段的指定主键表成功

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#69]
操作步骤：
创建一个只包含主键字段的指定主键表
结果：
success，查询结果，该表只包含一个主键字段
预期：
error，报错建表字段必须包含非主键字段
详细步骤：
![image](https://user-images.githubusercontent.com/76684843/105670726-744f2900-5f1c-11eb-9a1d-b2327f9cf42b.png)

**Comment by hgs19921112** [comment]
已修正
