### ISSUE TITLE
创建geopoint_ism、text 类型列，desc 查询展示为string_geopoint_ism，string_text_i

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#70]
操作步骤：
1.创建一个包含geopoint_ism、text字段类型的数据表
2.desc table 查询该表的列属性

结果：
查询的geopoint_ism、text字段属性与写入的属性值不一致 创建的属性值为geopoint_ism，实际查询的string_geopoint_ism
预期：
查询与实际写入应一致
详细请看图片：
![image](https://user-images.githubusercontent.com/76684843/105689372-a4ef8c80-5f35-11eb-8299-43f754ef4cfd.png)

**Comment by gleonSun** [comment]
已解决该 BUG，待后续测试
