### ISSUE TITLE
联合主键表无法查看表属性信息

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#77]
测试步骤：
1.创建一张联合主键表
2.SHOW TBLPROPERTIES table；查看表属性信息
结果：
1.操作成功
2.Error: java.util.NoSuchElementException: None.get (state=,code=0)
建议：
应可以查询表属性信息

详情如图
![image](https://user-images.githubusercontent.com/76684843/105955882-ee64e680-60b1-11eb-875b-3952fcb5b3b5.png)

**Comment by hgs19921112** [comment]
已解决
