### ISSUE TITLE
联合主键表无法查看建表语句

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#78]
测试步骤：
1.创建一张联合主键表
2.show create table table  查看建表语句
结果：
1.操作成功
2.Error: java.util.NoSuchElementException: None.get (state=,code=0)
建议：
应可以查询表属性信息

详情如图
![image](https://user-images.githubusercontent.com/76684843/105956191-64694d80-60b2-11eb-9b4c-924fa7390206.png)

**Comment by hgs19921112** [comment]
已解决
