### ISSUE TITLE
创建数据表，添加的表注释无法查看

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#79]
测试步骤：
1.创建一张数据表，并添加表注释
2.使用desc命令查看
结果：
1.数据表创建成功
2.desc只能查看表中列的注释信息
建议：
新增查看表注释方式以及增加表注释显示栏
![image](https://user-images.githubusercontent.com/76684843/105960544-5c141100-60b8-11eb-8f5f-b768f123f0e5.png)

**Comment by hgs19921112** [comment]
已修正
