### ISSUE TITLE
跨数据库，更新一张被禁用的数据表成功

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#82]
测试步骤：
1.禁用hert数据库中的一张数据表
2.更新这张被禁用的数据表
3.切换到djj数据库
4.更新hert数据库中被禁用的数据表
结果：
1.禁用成功。2.更新失败页面报错。3.成功切换。4.更新成功
预期：
第四步，应更新失败
详细步骤如图所示：
![c29b0d8d22876436a40b5eedfe2ced9](https://user-images.githubusercontent.com/76684843/106125698-69ec9380-6197-11eb-82fc-6d6fc0484093.png)

**Comment by hgs19921112** [comment]
根据步骤测试 表禁用后 update无法实现，怀疑在不同的库中有相同的数据表

**Comment by hgs19921112** [comment]
代码实现仅支持当前数据库表的更新 不支持快数据库表的更新
