### ISSUE TITLE
使用desc extended 查看表属性失败

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#83]
测试sql：
describe extended all_random;
desc extended all_random;
结果：
Error: java.lang.ArrayIndexOutOfBoundsException: 3 (state=,code=0)
期望：
应查询到表属性信息
![image](https://user-images.githubusercontent.com/76684843/106236647-462d5a00-6238-11eb-8620-c3f3a96ef02e.png)

**Comment by hgs19921112** [comment]
已解决
