### ISSUE TITLE
describe database FORMATTED 查看数据库属性失败

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#84]
测试步骤：
describe database FORMATTED djj;
结果：
Error: extraneous input 'djj' expecting <EOF>; line 1 pos 28 (state=,code=0)
期望;
应展示数据库的属性信息

![image](https://user-images.githubusercontent.com/76684843/106238534-fb154600-623b-11eb-9b61-7c58c809c02d.png)

**Comment by hgs19921112** [comment]
无 desc database formatted 语法
