### ISSUE TITLE
DESC FUNCTION FORMATTED  查看函数属性失败

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#87]
测试步骤：
desc FUNCTION FORMATTED max;
测试结果：
Error: extraneous input 'max' expecting <EOF>; line 1 pos 24 (state=,code=0)
预期：
应展示属性

**Comment by hgs19921112** [comment]
desc function的语法伟’DESCRIBE|DESC FUNCTION [EXTENDED] <function_name>‘ ，没有‘desc FUNCTION FORMATTED ’语法。
