### ISSUE TITLE
操作一张不存在的数据表，报错信息不一致

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#88]
测试步骤：
对一张不存在的表进行查询、插入数据、查看表状态、清空、删除、修改状态等操作
结果：
报错方式各不相同
建议：
因有设定数据表不存在的报错编码：12010 | OPERATION_TABLE_NOT_EXISTS | 数据表不存在，
所以建议对一张不存在的数据表进行的任意操作，统一提示报12010错误

![image](https://user-images.githubusercontent.com/76684843/106420908-a02b5b00-6496-11eb-991b-1ef4f9d0ca9b.png)

**Comment by hgs19921112** [comment]
报错信息已修改为存在描述
