### ISSUE TITLE
删除一张不存在的数据库，报错信息有误

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#89]
测试步骤：
删除一张不存在的数据库
结果：
Error: com.luxin.hydrogen.exception.HydrogenException: HydrogenErrorCode: 11010 (state=,code=0)
建议：
该报错为数据表不存在，应报错数据库不存在
![image](https://user-images.githubusercontent.com/76684843/106433876-bb549580-64ab-11eb-91ef-dd2b6c091c54.png)

**Comment by hgs19921112** [comment]
// DataBase Error
    /**
     * 数据库不存在
     **/
    OPERATION_DATABASE_NOT_EXISTS(11010),
    /***
报错对应没有错误
