### ISSUE TITLE
使用IF NOT EXISTS 覆盖创建已存在的数据库，数据库信息未更新

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#91]
测试步骤：
数据库hahaf已存在，无注释，覆盖创建并增加注释信息
1.create database IF NOT EXISTS hahaf comment 'this is test database';
2.desc database hahaf
结果：
执行sql success，desc查询，无新增的注释信息
期待：
新增信息覆盖
![image](https://user-images.githubusercontent.com/76684843/106442138-e47a2380-64b5-11eb-91b8-68b61b640141.png)

**Comment by hgs19921112** [comment]
if not exists问题
