### ISSUE TITLE
double类型范围wiki内容与实际操作返回不符

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#96]
文档注释：
wiki double类型 双精度浮点数64位 实际位数应为309位（包含符号位）
测试结果：
返回decimal类型，位数为38位（包含符号位）
![image](https://user-images.githubusercontent.com/76684843/106586043-f5449b00-6582-11eb-934e-e542a03bff5d.png)

**Comment by hgs19921112** [comment]
64为是占用的存储空间 报错38是精度问题
