### ISSUE TITLE
double类型 赋值整数问题

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#97]
测试步骤：
scort6 类型为double——ids
scort8 类型为double——sm
1.insert into all(scort6) values (2);
2.insert into all(scort6) values (99999999999999999999999999999999999999);
3.insert into all(scort8) values (array(2.221,2));
测试结果：
1.error。2.success  3.sucess  赋值整数，有的可以成功，有的不可以成功 
建议：
double类型，在数据范围内应能够赋值整形，经过类型判断自动转换为double类型

**Comment by hgs19921112** [comment]
已修复
