### ISSUE TITLE
double类型多值列赋值 空指针

### ISSUE THREAD

**Issue by Duanjia-jun** [lucene-cn/lxdb#99]
测试步骤：
insert into all(scort9) values (array(233333333333333.33333333333333333333333,2.3333333333333333333333333));
测试结果：
Error: java.lang.NullPointerException (state=,code=0)
![image](https://user-images.githubusercontent.com/76684843/106693845-42bc1900-6612-11eb-8024-43693afe66fd.png)
![image](https://user-images.githubusercontent.com/76684843/106693851-46e83680-6612-11eb-8596-9a66649a60af.png)

**Comment by hgs19921112** [comment]
表字段类型为double ，在spark中13242.353为Decimal，13242.353D为Double，如果数字不加D会导致数据类型转换失败。
例如：insert into all(scort9) values (array(233333333333333.33333333333333333333333D,2.3333333333333333333333333D));则完全没有问题，所以需要根据数据类型的不同添加后缀来防止类型转换错误。
